### ISSUE TITLE
jQuery lib

### ISSUE THREAD

**Issue by evliu** [JoshDellay/meteor-ladda-bootstrap#1]
Hey Josh, could you also attach the jQuery lib for completeness (also so I could use it?). Thx!

https://raw.githubusercontent.com/hakimel/Ladda/master/js/ladda.jquery.js

**Comment by JoshDellay** [comment]
I have added the above jQuery lib thanks for catching that.  I have also updated my atmosphere package as well.

**Comment by evliu** [comment]
Thanks for the quick update! Question: is there a reason why the min version is not used for the other files?
