### ISSUE TITLE
Issue Regarding Meteor Load Sequence

### ISSUE THREAD

**Issue by sotarules** [JoshDellay/meteor-ladda-bootstrap#3]
I'm not sure whether this is just a matter of my own setup, but in my case, the load order for the JavaScript files was crucial.

It was necessary for **spin.js** to load first followed by **ladda.js**.

When using unmodified meteor-ladda-bootstrap package, I encountered:

`uncaught TypeError: undefined is not a function`

in **createSpinner** when the function attempts to instantiate **Spinner**.

By renaming **spin.js** to **_spin.js** I was able to force the system to load **_spin.js** first.  In my case, this resolved the issue.  BTW I'm using Meteor 1.0.4.1 (bleeding edge at the time of this writing).

**Comment by chadokruse** [comment]
I'm also seeing this (on 1.0.4.2). Will try your fix @sotarules...thank you!

**Comment by JoshDellay** [comment]
Thanks for the find!
